name: gym
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.1
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^26.1.39
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/img/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
