// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvi_S9W8Noiwd3y_lhZCZgwp7ZjBqROmk',
    appId: '1:357972818639:web:586eb85e0a9fc5582515ba',
    messagingSenderId: '357972818639',
    projectId: 'gymzone-ad0ce',
    authDomain: 'gymzone-ad0ce.firebaseapp.com',
    storageBucket: 'gymzone-ad0ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-tQRJ5kAE-ZTLGx0HenLmP0E_B2htl8',
    appId: '1:357972818639:android:1006a7331da758162515ba',
    messagingSenderId: '357972818639',
    projectId: 'gymzone-ad0ce',
    storageBucket: 'gymzone-ad0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJkhYe974dbRHOfybTAc3-IcQ2zfKhyc',
    appId: '1:357972818639:ios:22d6980fbe8037f72515ba',
    messagingSenderId: '357972818639',
    projectId: 'gymzone-ad0ce',
    storageBucket: 'gymzone-ad0ce.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJkhYe974dbRHOfybTAc3-IcQ2zfKhyc',
    appId: '1:357972818639:ios:22d6980fbe8037f72515ba',
    messagingSenderId: '357972818639',
    projectId: 'gymzone-ad0ce',
    storageBucket: 'gymzone-ad0ce.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvi_S9W8Noiwd3y_lhZCZgwp7ZjBqROmk',
    appId: '1:357972818639:web:6e0b986191a461f02515ba',
    messagingSenderId: '357972818639',
    projectId: 'gymzone-ad0ce',
    authDomain: 'gymzone-ad0ce.firebaseapp.com',
    storageBucket: 'gymzone-ad0ce.appspot.com',
  );
}
