// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQjCGJzlhBWTsm0stY5C_USLONkbtN-c',
    appId: '1:1062442899194:web:a67b2659edcbfe0652db43',
    messagingSenderId: '1062442899194',
    projectId: 'gymzone-107b5',
    authDomain: 'gymzone-107b5.firebaseapp.com',
    storageBucket: 'gymzone-107b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkrUURVwIXYvFREpNje0AuMBxmGEzqcY8',
    appId: '1:1062442899194:android:c4835ce5363f48e552db43',
    messagingSenderId: '1062442899194',
    projectId: 'gymzone-107b5',
    storageBucket: 'gymzone-107b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9duUyAV9xUmyHU_8l-705YXFl4Iy5OA',
    appId: '1:1062442899194:ios:2ffed6da3921daa452db43',
    messagingSenderId: '1062442899194',
    projectId: 'gymzone-107b5',
    storageBucket: 'gymzone-107b5.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9duUyAV9xUmyHU_8l-705YXFl4Iy5OA',
    appId: '1:1062442899194:ios:2ffed6da3921daa452db43',
    messagingSenderId: '1062442899194',
    projectId: 'gymzone-107b5',
    storageBucket: 'gymzone-107b5.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQjCGJzlhBWTsm0stY5C_USLONkbtN-c',
    appId: '1:1062442899194:web:954e57ba8695850952db43',
    messagingSenderId: '1062442899194',
    projectId: 'gymzone-107b5',
    authDomain: 'gymzone-107b5.firebaseapp.com',
    storageBucket: 'gymzone-107b5.appspot.com',
  );

}